micronaut:
  application:
    name: finance-api-rest
datasources:
  default:
    url: jdbc:h2:mem:finances-dev;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:file:~/db/finances-dev;CIPHER=AES;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    #password: 'file-pswd user-pswd'
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
#      javax.persistence.schema-generation:
#        scripts:
#          action: drop-and-create
#          create-target: build/db/create.sql
#          create-source: metadata
#          drop-target: build/db/drop.sql
#          drop-source: metadata
